# Generated by Django 4.2 on 2024-07-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Phone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
